%YAML:1.0

# =====================
# Common Parameters
# =====================
imu_topic: "/imu0"
image_topic: "/cam0/image_raw"
output_path: "/home/lxk/testdata1/Trajactory/"

# =====================
# Camera Calibration
# =====================
model_type: PINHOLE
camera_name: camera
image_width: 512
image_height: 512
projection_parameters:
   fx: 190.97847715128717
   fy: 190.9733070521226
   cx: 254.93170605935475
   cy: 256.8974428996504

# =====================
# Extrinsic Calibration (IMU to Camera)
# =====================
estimate_extrinsic: 0
ex_calib_result_path: "/config/tum/ex_calib_result.yaml"

extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.9995146589929846, 0.0075842033363785165, -0.030214670573904204,
           0.029940114644659861, -0.034023430206013172, -0.99897246995704592,
          -0.0086044170750674241, -0.99939225835343004, 0.033779845322755464]

extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.044511917113940799, -0.073197096234105752, -0.047972907300764499]

# =====================
# Feature Tracker Parameters
# =====================
max_cnt: 150
min_dist: 25
freq: 0                       # use all frames from rosbag
F_threshold: 1.0
show_track: 1
equalize: 1
fisheye: 0                   # model_type is PINHOLE, must set this to 0

# =====================
# Optimization Parameters
# =====================
max_solver_time: 0.04
max_num_iterations: 8
keyframe_parallax: 10.0

# =====================
# IMU Noise Parameters
# =====================
acc_n: 0.04
gyr_n: 0.004
acc_w: 0.0004
gyr_w: 2.0e-5
g_norm: 9.80766

# =====================
# Loop Closure Parameters
# =====================
loop_closure: 1
load_previous_pose_graph: 0
fast_relocalization: 0
pose_graph_save_path: "/home/lxk/testdata1/Trajactory/"

# =====================
# Time Offset Estimation
# =====================
estimate_td: 0
td: 0.0

# =====================
# Rolling Shutter Parameters
# =====================
rolling_shutter: 0
rolling_shutter_tr: 0

# =====================
# Visualization Parameters
# =====================
save_image: 1
visualize_imu_forward: 0
visualize_camera_size: 0.4

# =====================
# Line Feature Parameters
# =====================
use_line: 0
optimize_lines: 0
add_line_to_marg: 0
line_plucker_parameter: 6

